import test from 'node:test';
import assert from 'node:assert/strict';
import cp from 'node:child_process';
import {syncBuiltinESMExports} from 'node:module';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {mkdtemp,realpath,chmod,rm,readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {LinuxBrowserExecutor} from '../../../dist/packages/linux-browser/src/index.js';
import {canonicalJson,digest} from '../../../dist/packages/contracts/src/index.js';
const assets=process.env.TRELLIS_BROWSER_ASSETS;
const fixture='<!doctype html><title>synthetic</title>';
const fakeId='d'.repeat(64);
function fakeDocker(t,behavior={}){const calls=[],containers=new Map();const old=cp.spawn;cp.spawn=(bin,args,options)=>{
 assert.equal(bin,'/usr/local/bin/docker');assert.deepEqual(args.slice(0,2),['--context','desktop-linux']);assert.equal(options.env.HOME,process.env.HOME);assert.equal(options.env.CODEX_HOME,process.env.CODEX_HOME);
 const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>{queueMicrotask(()=>child.emit('close',null));return true;};const command=args.slice(2);calls.push(command);
 queueMicrotask(async()=>{try{let result={code:0,out:'',err:''};const [kind,op]=command;assert.equal(kind,'container');
 if(op==='create'){await behavior.beforeCreate?.();const nonce=command[command.indexOf('--label')+1].split('=')[1];const mount=command[command.indexOf('--mount')+1];const input=mount.split('source=')[1].split(',target=')[0];containers.set(fakeId,{id:fakeId,label:nonce,image:command.at(-2),running:false,input});result.out=behavior.lostCreate?'':fakeId+'\n';}
 else if(op==='inspect'){const c=containers.get(command.at(-1));result=c?{code:0,out:JSON.stringify(c),err:''}:{code:1,out:'',err:'No such container'};}
 else if(op==='start'){const c=containers.get(command.at(-1));assert(c);c.running=true;await behavior.beforeStart?.();const req=JSON.parse(await readFile(join(c.input,'request.json')));const report={format:'trellis/test-report/v0.7-alpha',operationId:req.operationId,requestDigest:req.requestDigest,manifestDigest:req.manifestDigest,artifactDigest:req.artifact.digest,checks:['add-job','change-stage','reload','export'].map(id=>({id,passed:true,observation:'synthetic transport only'})),exported:{digest:digest('export'),bytes:6},exitCode:0,stdout:{digest:digest(''),bytes:0},stderr:{digest:digest(''),bytes:0},scratchBytesPeak:12};result.out=JSON.stringify({report,evidence:{groupGone:true,boundary:Object.fromEntries(['artifactRead','scratchWrite','artifactWrite','rootWrite','outsideRead','daemonSocket','tcpDenied'].map(x=>[x,true])),browserSandbox:[{Seccomp:'2',Seccomp_filters:'2',NoNewPrivs:'1'}],containerSelf:{Seccomp_filters:'1'}}});c.running=false;}
 else if(op==='stop')containers.get(command.at(-1)).running=false;
 else if(op==='rm'){if(behavior.removeFails)result={code:1,out:'',err:'synthetic removal failure'};else containers.delete(command.at(-1));}
 else throw Error('unexpected command');child.stdout.end(result.out);child.stderr.end(result.err);child.emit('close',result.code);
 }catch(e){child.emit('error',e);child.emit('close',1);}});return child;
 };syncBuiltinESMExports();t.after(()=>{cp.spawn=old;syncBuiltinESMExports();});return {calls,containers};}
async function installation(t){const stateRoot=await realpath(await mkdtemp(join(tmpdir(),'trellis-browser-unit-')));await chmod(stateRoot,0o700);t.after(()=>rm(stateRoot,{recursive:true,force:true}));let browserRoot,librariesRoot;if(assets){browserRoot=resolve(assets,'headless-shell/extracted/chrome-headless-shell-linux-arm64');librariesRoot=resolve(assets,'runtime-libraries/lib');}else{const resources=await realpath(await mkdtemp(join(tmpdir(),'trellis-browser-assets-')));t.after(()=>rm(resources,{recursive:true,force:true}));browserRoot=join(resources,'browser');librariesRoot=join(resources,'libraries');await mkdir(browserRoot);await mkdir(librariesRoot);}return {format:'trellis/linux-browser-installation/v0.7-alpha',stateRoot,browserRoot,librariesRoot};}
// Unit-only construction bypasses public asset provisioning; all transport is fake.
// Setting TRELLIS_BROWSER_ASSETS also exercises public open and every actual dependency pin.
const makeExecutor=async i=>assets?LinuxBrowserExecutor.open(i):new LinuxBrowserExecutor(i,{browserFiles:[],libraries:[],libraryLinks:[]},Buffer.from('synthetic runner'),Buffer.from('{}'),canonicalJson({format:'trellis/registered-test/v0.7-alpha',testId:'craft-shop-ui-v1',testerDigest:digest('synthetic tester'),environmentDigest:digest('synthetic environment'),criteria:['add-job','change-stage','reload','export'],limits:{timeoutMs:25000,outputBytes:16384,artifactBytes:65536}}));
function request(executor,suffix='one'){const scope={workspaceId:'synthetic',runId:suffix,taskId:'test'},writeOperationKey=digest(suffix),operationId=digest(canonicalJson({scope,writeOperationKey})),manifest=JSON.parse(executor.manifest),at=Date.now();const base={format:'trellis/test-request/v0.7-alpha',operationId,scope,candidateRevision:digest('candidate'),ownerEpoch:1,writeRequestId:'request',writeOperationKey,writeActionDigest:digest('action'),manifest,manifestDigest:digest(executor.manifest),artifact:{path:'ignored.html',content:fixture,digest:digest(fixture),bytes:Buffer.byteLength(fixture)}};return {...base,requestDigest:digest(canonicalJson(base)),launcherId:'synthetic',startedAtMs:at,deadlineMs:at+25000};}

test('installation rejects unknown command overrides and nonprivate state',async t=>{const i=await installation(t);await assert.rejects(LinuxBrowserExecutor.open({...i,argv:['bad']}),/INVALID_INSTALLATION/);await chmod(i.stateRoot,0o755);await assert.rejects(LinuxBrowserExecutor.open(i),/PRIVATE_DIRECTORY/);});
test('real pinned asset validation, immutable snapshot, cleanup, replay refusal and restart reap',async t=>{const i=await installation(t),transport=fakeDocker(t);const executor=await makeExecutor(i),r=request(executor);const pending=executor.execute(r,new AbortController().signal);r.artifact.content='mutated after call';const report=await pending;assert.equal(report.exitCode,0);assert.equal(report.scratchRemoved,true);assert.equal(transport.containers.size,0);assert.equal(transport.calls.filter(a=>a[1]==='start').length,1);await assert.rejects(executor.execute(request(executor),new AbortController().signal),/EEXIST/);const restarted=await makeExecutor(i);await restarted.reap(r.operationId);await assert.rejects(restarted.reap(digest('unknown')),/UNKNOWN_OPERATION/);});
test('wrong artifact digest and stale deadline refuse before transport',async t=>{const i=await installation(t),transport=fakeDocker(t),e=await makeExecutor(i);const r=request(e);r.artifact.digest=digest('wrong');await assert.rejects(e.execute(r,new AbortController().signal));const stale=request(e);stale.startedAtMs-=30000;stale.deadlineMs-=30000;await assert.rejects(e.execute(stale,new AbortController().signal),/EXPIRED/);assert.equal(transport.calls.length,0);});
test('lost create acknowledgement remains held across new executor and never adopts by name',async t=>{const i=await installation(t),transport=fakeDocker(t,{lostCreate:true}),e=await makeExecutor(i),r=request(e);await assert.rejects(e.execute(r,new AbortController().signal),/CREATION_UNCERTAIN/);const restarted=await makeExecutor(i);await assert.rejects(restarted.reap(r.operationId),/CREATION_UNCERTAIN/);assert.equal(transport.calls.filter(a=>a[1]==='start'||a[1]==='rm').length,0);assert.equal(transport.containers.size,1);});
test('reap fences paused creation, waits for identity and prevents launch',async t=>{let release,entered;const reached=new Promise(r=>entered=r),pause=new Promise(r=>release=r);const i=await installation(t),transport=fakeDocker(t,{beforeCreate:async()=>{entered();await pause;}}),e=await makeExecutor(i),r=request(e);const execution=e.execute(r,new AbortController().signal);execution.catch(()=>{});await reached;const cleanup=e.reap(r.operationId);release();await cleanup;await assert.rejects(execution,/CANCELLED_OR_EXPIRED/);assert.equal(transport.calls.filter(a=>a[1]==='start').length,0);assert.equal(transport.containers.size,0);});
test('cleanup failure cannot report success or clear durable claim',async t=>{const i=await installation(t),transport=fakeDocker(t,{removeFails:true}),e=await makeExecutor(i),r=request(e);await assert.rejects(e.execute(r,new AbortController().signal),/REMOVE_FAILED/);assert.equal(transport.containers.size,1);const j=JSON.parse(await readFile(join(i.stateRoot,r.operationId.slice(7),'journal.json')));assert.equal(j.stage,'CREATED');});
test('foreign recorded identity is refused; no bare PID or name cleanup',async t=>{const i=await installation(t),transport=fakeDocker(t),e=await makeExecutor(i),r=request(e),dir=join(i.stateRoot,r.operationId.slice(7));await mkdir(dir,{mode:0o700});await writeFile(join(dir,'journal.json'),JSON.stringify({version:1,id:r.operationId,requestDigest:r.requestDigest,nonce:'a'.repeat(36),cid:fakeId,stage:'CREATED'}));transport.containers.set(fakeId,{id:fakeId,label:'different',image:'different',running:true});await assert.rejects(e.reap(r.operationId),/OWNERSHIP_MISMATCH/);assert.equal(transport.calls.filter(a=>a[1]==='rm'||a[1]==='stop').length,0);});
test('fresh executor reaps a durable known container identity after launcher loss',async t=>{const i=await installation(t),transport=fakeDocker(t),e=await makeExecutor(i),r=request(e),dir=join(i.stateRoot,r.operationId.slice(7)),nonce='12345678-1234-1234-1234-123456789abc';await mkdir(dir,{mode:0o700});await mkdir(join(dir,'input'));await writeFile(join(dir,'input/artifact'),'synthetic');await writeFile(join(dir,'journal.json'),JSON.stringify({version:1,id:r.operationId,requestDigest:r.requestDigest,nonce,cid:fakeId,stage:'CREATED'}));transport.containers.set(fakeId,{id:fakeId,label:nonce,image:'node@sha256:64af3819f9275802414d7cdc38c27e9d82bd564dec4d4da87d008255d36c63b4',running:true});const restarted=await makeExecutor(i);await restarted.reap(r.operationId);assert.equal(transport.containers.size,0);assert.deepEqual(transport.calls.filter(a=>a[1]==='stop'||a[1]==='rm').map(a=>a.at(-1)),[fakeId,fakeId]);assert.equal(JSON.parse(await readFile(join(dir,'journal.json'))).stage,'REAPED');assert(!(await readdir(dir)).includes('input'));});
test('cancellation before accepted launch creates no container',async t=>{const i=await installation(t),transport=fakeDocker(t),e=await makeExecutor(i),r=request(e),c=new AbortController();c.abort();await assert.rejects(e.execute(r,c.signal),/CANCELLED/);assert.equal(transport.calls.length,0);});
test('durable pre-create ambiguity refuses foreign cleanup instead of allowing a late launch',async t=>{const i=await installation(t),transport=fakeDocker(t),e=await makeExecutor(i),r=request(e),dir=join(i.stateRoot,r.operationId.slice(7));await mkdir(dir,{mode:0o700});await writeFile(join(dir,'journal.json'),JSON.stringify({version:1,id:r.operationId,requestDigest:r.requestDigest,nonce:'12345678-1234-1234-1234-123456789abc',cid:null,stage:'CREATING'}));await assert.rejects(e.reap(r.operationId),/CREATION_UNCERTAIN/);assert((await readdir(dir)).includes('fence'));assert.equal(transport.calls.length,0);});
test('FIFO journal refuses promptly without a writer or Docker dispatch',async t=>{const i=await installation(t),e=await makeExecutor(i),r=request(e),dir=join(i.stateRoot,r.operationId.slice(7));await mkdir(dir,{mode:0o700});cp.execFileSync('/usr/bin/mkfifo',[join(dir,'journal.json')]);const transport=fakeDocker(t);const started=Date.now();await assert.rejects(e.reap(r.operationId),/INVALID_FILE/);assert(Date.now()-started<1000);assert.equal(transport.calls.length,0);});
