// Reviewed frozen copy of packages/workbench/scenarios/craft-shop-v1/r1.
// Packaged in the runtime closure; tests compare every byte to the Workbench source.
export const DEMO_SCENARIO_DIGEST = 'sha256:bc620b68e6c6a147f0e121327d5175a50c0b89ea23514e3202b8464ccb6827b8';
export const DEMO_SOURCE_BYTES = Object.freeze({
  "scenario": "{\n  \"format\": \"trellis/workbench-scenario/v0.7-alpha\",\n  \"id\": \"craft-shop-v1\",\n  \"revision\": \"r1\",\n  \"classification\": \"synthetic\",\n  \"brief\": {\n    \"asset\": \"project-brief\",\n    \"digest\": \"sha256:630be0f0a66f0c0e2c445ad476a3f254894e43c045821b6c5a26c592f51a5c6a\",\n    \"bytes\": 667\n  },\n  \"inputs\": [\n    {\n      \"asset\": \"contract\",\n      \"digest\": \"sha256:209ec76881da3c3dde0ff52a569dd7a0991dd33d9a0aa85226a9a42bee510dac\",\n      \"bytes\": 1764\n    },\n    {\n      \"asset\": \"orders\",\n      \"digest\": \"sha256:b98257ea28d6abca6d9ffdc6f2dd1341cc2768fb28ef7063718910d463881800\",\n      \"bytes\": 241\n    }\n  ],\n  \"testId\": \"craft-shop-ui-v1\",\n  \"criteria\": [\n    \"add-job\",\n    \"change-stage\",\n    \"reload\",\n    \"export\"\n  ],\n  \"taskCount\": 2,\n  \"writePaths\": [\n    \"output/design/index.html\",\n    \"output/job-board/index.html\"\n  ]\n}\n",
  "project-brief": "Build a self-contained job board for a fictional craft shop. Use only the supplied synthetic orders.\n\nThe board must add jobs, change stages, retain jobs after reload, and export matching JSON. Follow the fixed browser contract.\n\nCreate a functional prototype, then refine its clarity and accessibility using the accepted HTML handoff. Choose appropriate roles and write their prompts and skills.\n\nUse one approved HTML write and the registered craft-shop-ui-v1 test per task. Keep one attempt, sequential dependencies, a 25 percent reserve, and no paid fallback.\n\nDo not add marketplace connections, native commands, external resources, telemetry, or customer data.\n",
  "contract": "# Craft-shop browser contract\n\nThe alpha demo is one self-contained HTML file. It uses synthetic jobs and needs no external resource or marketplace connection.\n\nThe trusted browser test uses the following interface. The application must preserve these identifiers when it changes its appearance.\n\n| Element | Contract |\n| --- | --- |\n| Job form | `form#job-form` |\n| Title input | `input#job-title`, with a visible label and required value |\n| Add control | A submit button inside `#job-form` |\n| Jobs container | `#jobs` |\n| Job row | An element inside `#jobs` with a stable `data-job-id` |\n| Visible title | `.job-title` inside each row |\n| Stage control | `select.job-stage` inside each row |\n| Stage values | `queued`, `in-progress`, and `done` |\n| Export control | `button#export-jobs` |\n\nA new job starts at `queued`. Its identifier remains stable after a stage change and page reload. The application stores jobs in localStorage.\n\nThe export button downloads `trellis-jobs.json`. The file contains one JSON object with `version: 1` and a `jobs` array.\n\nEach exported job has exactly `id`, `title`, and `stage`. The identifier and title are strings. The stage uses one of the three declared values.\n\nThe trusted test adds a unique synthetic title through the form. It changes that row to `in-progress`, reloads the page, and downloads the export.\n\nThe test compares the visible row and downloaded record. It requires the same identifier, exact title, and changed stage in both places.\n\nA passing test requires all four behaviors and successful process cleanup. Application text or model claims cannot supply the result.\n\nThis contract tests one browser session and origin. It does not prove durability after a browser restart or access from another machine.\n",
  "orders": "{\"version\":1,\"jobs\":[{\"id\":\"demo-001\",\"title\":\"Willow basket for Mira\",\"stage\":\"queued\"},{\"id\":\"demo-002\",\"title\":\"Carved trail sign for Rowan\",\"stage\":\"in-progress\"},{\"id\":\"demo-003\",\"title\":\"Three linen pouches for Fern\",\"stage\":\"done\"}]}\n"
});
