// Host/process seams only; the installed private core, pure installation and refusal wire remain real.
import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';
import {digest,byteDigest} from '../../../dist/packages/claude-adapter/src/policy.js';
import {STARTUP_CLOCK,claudeStartupLaunchRevision} from '../../../dist/packages/codex-adapter/src/startup-deadline.js';
const key='claude-core-synthetic';globalThis[key]={};const state=globalThis[key];
const hostURL=new URL('../../../dist/packages/claude-adapter/src/host.js',import.meta.url).href;
const hostShim='data:text/javascript,'+encodeURIComponent(`export {captureHost,candidateEnvironment,environmentRevision} from ${JSON.stringify(hostURL)};export const measureHost=(...a)=>globalThis[${JSON.stringify(key)}].measure(...a);export const privateWorkspace=(...a)=>globalThis[${JSON.stringify(key)}].workspace(...a);`);
const guardianShim='data:text/javascript,'+encodeURIComponent(`export const startGuardian=(...a)=>globalThis[${JSON.stringify(key)}].start(...a);`);
const hooks=registerHooks({resolve(s,c,n){if(c.parentURL?.endsWith('/claude-adapter/src/adapter-core.js')){if(s==='./host.js')return{url:hostShim,shortCircuit:true};if(s.endsWith('/supervisor.js'))return{url:guardianShim,shortCircuit:true};}return n(s,c);}});
const {ClaudeAdapterCore}=await import('../../../dist/packages/claude-adapter/src/adapter-core.js');hooks.deregister();
const paths=['policy','observation','protocol','installation','boundary','host','wire','adapter-core','controlled-exchange','limited-policy','limited-protocol','limited-wire'].map(n=>`dist/packages/claude-adapter/src/${n}.js`).concat(['startup-deadline','supervisor','guardian','safe','policy'].map(n=>`dist/packages/codex-adapter/src/${n}.js`),['dist/packages/mcp-connections/src/darwin-boot-session.js','dist/packages/mcp-connections/src/model.js','dist/packages/contracts/src/index.js']).sort();
const later=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};};
function setup(){
 const h='a'.repeat(64),now=Date.now(),abort=new AbortController(),inventory=paths.map(path=>({path,sha256:h,bytes:1}));
 const host={nativePath:'/synthetic/claude',nativeSha256:h,nativeVersion:'2.1.292',artifactRoot:'/synthetic/artifact',workRoot:'/synthetic/work',inventory,artifactRevision:digest(inventory)};
 const input={launcherId:'launcher',modelRoute:'claude:claude-sonnet-5-5:high',prompt:'Synthetic only',issuedAtMs:now-100,expiresAtMs:now+30000,accountBindingRevision:h,requestRevision:h,parentOutputRevision:null};
 const stats={measure:0,workspace:0,starts:0,writes:0,ends:0,terminates:0,closes:0,checks:0,consumes:0};const done=later();
 state.measure=async c=>{stats.measure++;return{format:'bowerloom/claude-measurement/v1',nativePath:c.nativePath,nativeSha256:c.nativeSha256,nativeVersion:c.nativeVersion,artifactRevision:c.artifactRevision,inventory:c.inventory,measuredAtMs:Date.now()};};
 state.workspace=async()=>{stats.workspace++;return{cwd:'/synthetic/work',async verify(){},async close(){stats.closes++;}};};
 state.start=async(job,signal,chunk)=>{stats.starts++;stats.job=job;chunk('stdout',Buffer.from('{"type":"result","result":"synthetic"}'));return{guardianPid:100,identity:{pid:101,groupId:101,ownershipDigest:h},done:done.promise,write(){stats.writes++;},end(){stats.ends++;},async terminate(){stats.terminates++;done.resolve({code:0,reason:null,leaderReaped:true,groupGone:true});}};};
 const gate={async check(){stats.checks++;},assertCurrent(){assert.equal(abort.signal.aborted,false);},consume(p){stats.consumes++;const wall=Date.now(),hr=process.hrtime.bigint(),runtime={executable:process.execPath,sha256:h,nodeVersion:'v24.11.0',uvVersion:'1.51.0',platform:'darwin',arch:'arm64'};return{format:'bowerloom/claude-startup/v1',clock:STARTUP_CLOCK,runtime,accountBindingDigest:h,promptDigest:byteDigest(input.prompt),modelRoute:input.modelRoute,proposalPlanRevision:p.launchPlanRevision,launchPlanRevision:claudeStartupLaunchRevision(p.launchPlanRevision,runtime,input.modelRoute),admission:{format:'bowerloom/admission-dispatch/v1',binding:{installationId:'install',databaseName:'db',admissionSchema:'trellis_test',launcherId:'launcher',accountId:'account',accountAlias:'alias',requestDigest:'sha256:'+h,authorizationRevision:h,expiresAtMs:now+30000},reservationId:'reservation',requestDigest:'sha256:'+h,claimedAtMs:wall,parentWallMs:wall,parentHrNs:String(hr),notAfterWallMs:now+30000,notAfterHrNs:String(hr+20000000000n)}};}};
 return{host,input,stats,done,abort,gate,runner:()=>new ClaudeAdapterCore(host,gate)};
}
test('real core prepares fixed denied-tools argv and one prompt; unqualified response refuses after reaping',async()=>{const f=setup(),core=f.runner(),p=await core.start(f.input,f.abort.signal);f.done.resolve({code:0,reason:null,leaderReaped:true,groupGone:true});await assert.rejects(p.result,{message:'CLAUDE_LAUNCH_REFUSED'});assert.equal(f.stats.starts,1);assert.equal(f.stats.writes,1);assert.equal(f.stats.ends,1);assert.equal(f.stats.consumes,1);assert.ok(f.stats.job.argv.includes('--restricted'));assert.deepEqual(f.stats.job.env,{DISABLE_UPDATES:'1',LANG:'C'});assert.deepEqual(await core.quiescence(),{cleanup:'verified'});assert.equal(core.retainedOwners(),0);await p.terminate();assert.equal(f.stats.terminates,1);});
test('pre-abort and preparation cancellation cannot produce a late process',async()=>{for(const mode of ['pre','measure']){const f=setup(),core=f.runner();if(mode==='pre')f.abort.abort();else state.measure=async()=>{f.abort.abort();throw Error('PRIVATE');};await assert.rejects(core.start(f.input,f.abort.signal));assert.equal(f.stats.starts,0);assert.equal(f.stats.consumes,0);}});
test('unknown prehandle start retains uncertain ownership and permanently quarantines',async()=>{const f=setup();state.start=async()=>{f.stats.starts++;throw Error('PRIVATE_OPEN');};const core=f.runner();await assert.rejects(core.start(f.input,f.abort.signal),{message:'CLAUDE_LAUNCH_REFUSED'});assert.deepEqual(await core.quiescence(),{cleanup:'unverified'});assert.ok(core.retainedOwners()>0);await assert.rejects(core.start(f.input,f.abort.signal));assert.equal(f.stats.starts,1);});
test('cleanup refusal keeps actual owners and never reports verified',async()=>{const f=setup(),base=state.start;state.start=async(...a)=>({...await base(...a),async terminate(){throw Error('PRIVATE_CLEANUP');}});const core=f.runner(),p=await core.start(f.input,f.abort.signal);f.done.resolve({code:0,reason:null,leaderReaped:true,groupGone:true});await assert.rejects(p.result);assert.equal((await core.quiescence()).cleanup,'unverified');assert.ok(core.retainedOwners()>0);});
test('late fulfilled start on cancellation sends no prompt and cleans its actual handle',async()=>{const f=setup(),entered=later(),pending=later(),base=state.start;state.start=async(...a)=>{entered.resolve();await pending.promise;return base(...a);};const core=f.runner(),p=core.start(f.input,f.abort.signal);await entered.promise;f.abort.abort();pending.resolve();await assert.rejects(p);assert.equal(f.stats.writes,0);assert.equal(f.stats.ends,0);assert.equal(f.stats.terminates,1);assert.equal((await core.quiescence()).cleanup,'verified');});
test('final authority refresh follows both last host awaits and precedes consumption',async()=>{
 for(const boundary of ['measurement','workspace']){
  const f=setup();let revoked=false,measures=0;const measure=state.measure;
  state.measure=async(...args)=>{const value=await measure(...args);if(++measures===2&&boundary==='measurement')revoked=true;return value;};
  state.workspace=async()=>({cwd:'/synthetic/work',async verify(){if(boundary==='workspace')revoked=true;},async close(){f.stats.closes++;}});
  f.gate.check=async()=>{f.stats.checks++;if(revoked)throw Error('PRIVATE_REVOKED');};
  const core=f.runner();await assert.rejects(core.start(f.input,f.abort.signal),{message:'CLAUDE_LAUNCH_REFUSED'});
  assert.equal(revoked,true);assert.equal(f.stats.checks,2);assert.equal(f.stats.consumes,0);assert.equal(f.stats.starts,0);assert.equal(f.stats.writes,0);assert.equal(f.stats.ends,0);assert.equal((await core.quiescence()).cleanup,'verified');
 }
});
test('private core policy discriminator accepts no decoder callback, boolean override or unknown policy',()=>{const f=setup();let called=0;for(const p of [true,{kind:'other'},{kind:'strict',decoder(){called++;}},{kind:'limited',grant:{},qualification:{},ownerApproval:{}}])assert.throws(()=>new ClaudeAdapterCore(f.host,f.gate,p));assert.equal(called,0);assert.equal(f.stats.starts,0);assert.equal(f.stats.measure,0);});
