// SYNTHETIC host/process/provider seams. Real controller, core, projector, installation,
// startup protocol and PostgresAdmission transactions run; no actual provider/native/DB.
import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import {EventEmitter} from 'node:events';import {readFile} from 'node:fs/promises';
import {digest,byteDigest,canonical,ROUTES,POLICY_VERSION} from '../../../dist/packages/claude-adapter/src/policy.js';
import {createObservationProjector} from '../../../dist/packages/claude-adapter/src/observation.js';
import {environmentRevision} from '../../../dist/packages/claude-adapter/src/host.js';
import {LIMITED_POLICY,LIMITED_PROFILE_REVISION,OWNER_PROPOSAL,LIMITED_WIRE_PROFILE,limitedEnvironmentRevision} from '../../../dist/packages/claude-adapter/src/limited-policy.js';
import {validateResponseEvidence} from '../../../dist/packages/claude-adapter/src/protocol.js';
import {PostgresAdmission,createAccount,acceptObservation} from '../../../dist/packages/admission/src/index.js';
import {digest as ledgerDigest,canonicalJson} from '../../../dist/packages/contracts/src/index.js';
const key='claude-exchange-synthetic',state={validateResponseEvidence};globalThis[key]=state;
const base=new URL('../../../dist/packages/claude-adapter/src/',import.meta.url);
const shim=source=>'data:text/javascript,'+encodeURIComponent(source);
const hostShim=shim(`export {captureHost,candidateEnvironment,environmentRevision} from ${JSON.stringify(new URL('host.js',base).href)};export const measureHost=(...a)=>globalThis[${JSON.stringify(key)}].measure(...a);export const privateWorkspace=(...a)=>globalThis[${JSON.stringify(key)}].workspace(...a);`);
const guardianShim=shim(`export const startGuardian=(...a)=>globalThis[${JSON.stringify(key)}].start(...a);`);
const wireShim=shim(`export {decodeEnvelope,WIRE_PROFILE} from ${JSON.stringify(new URL('wire.js',base).href)};export class ClaudeWire{feed(){}finish(expected){return globalThis[${JSON.stringify(key)}].response(expected);}}`);
const hooks=registerHooks({resolve(s,c,n){if(c.parentURL?.includes('/claude-adapter/src/')){if(s==='./host.js'&&(c.parentURL.endsWith('controlled-exchange.js')||c.parentURL.endsWith('adapter-core.js')))return{url:hostShim,shortCircuit:true};if(s.endsWith('/supervisor.js')&&c.parentURL.endsWith('adapter-core.js'))return{url:guardianShim,shortCircuit:true};if(s==='./wire.js'&&c.parentURL.endsWith('adapter-core.js'))return{url:wireShim,shortCircuit:true};}return n(s,c);}});
const {ClaudeControlledExchange,LimitedClaudeControlledExchange,exchangePrompt}=await import('../../../dist/packages/claude-adapter/src/controlled-exchange.js');hooks.deregister();
const paths=['policy','observation','protocol','installation','boundary','host','wire','adapter-core','controlled-exchange','limited-policy','limited-protocol','limited-wire'].map(n=>`dist/packages/claude-adapter/src/${n}.js`).concat(['startup-deadline','supervisor','guardian','safe','policy'].map(n=>`dist/packages/codex-adapter/src/${n}.js`),['dist/packages/mcp-connections/src/darwin-boot-session.js','dist/packages/mcp-connections/src/model.js','dist/packages/contracts/src/index.js']).sort();
const deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject};},tick=()=>new Promise(r=>setImmediate(r));
function pool(){let stored=createAccount('account',['alias'],{thresholdPercent:95,maxWorkers:2,maxObservationAgeMs:5000,headroomPercent:2,admittedRoutes:[...ROUTES],completedResetPolicy:'hold'}),tail=Promise.resolve();return{hook:null,snapshot:()=>structuredClone(stored),async connect(){const before=tail,lock=deferred();tail=lock.promise;await before;let staged,released=false;const c=new EventEmitter();c.release=()=>{assert.equal(released,false);released=true;lock.resolve();};c.query=async(sql,v)=>{const execute=()=>{if(sql.startsWith('BEGIN'))staged=structuredClone(stored);else if(sql.startsWith('SET LOCAL')){}else if(sql==='SELECT current_database() AS name')return{rows:[{name:'synthetic'}]};else if(sql.includes('.metadata FOR SHARE'))return{rows:[{singleton:true,version:1}]};else if(sql.includes('WHERE account_id=(SELECT'))return{rows:[{account_id:staged.accountId,version:1,state:structuredClone(staged),checksum:ledgerDigest(canonicalJson(staged))}]};else if(sql.startsWith('UPDATE'))staged=JSON.parse(v[1]);else if(sql==='COMMIT')stored=structuredClone(staged);else if(sql==='ROLLBACK')staged=undefined;else throw Error('UNEXPECTED_SYNTHETIC_SQL');return{rows:[]};};if(this.hook){const out=await this.hook(sql,v,execute);if(out!==undefined)return out;}return execute();};return c;}};}
const signed=b=>({...b,revision:digest(b)});
async function setup(){
 const H='a'.repeat(64),now=Date.now(),db=pool(),abort=new AbortController(),stats={starts:0,writes:0,ends:0,terminates:0,reads:0,lookups:0,qualifications:0,envelopes:[],events:[],observations:[]};
 const root=new URL('../../../../campaign/sagespec/dual-harness-trial-01/bundle/.bowerloom/teams/sagespec-bowerloom/',import.meta.url);
 const roleAssets=Object.fromEntries(await Promise.all(Object.entries({techLead:'prompts/tech-lead.md',knowledgeLibrary:'prompts/knowledge-library.md',agreement:'assets/working-agreement.md',practice:'skills/project-practice.md',policy:'operating-policy.yaml'}).map(async([k,p])=>[k,await readFile(new URL(p,root),'utf8')])));
 const inventory=paths.map(path=>({path,sha256:H,bytes:1})),host={nativePath:'/synthetic/claude',nativeSha256:H,nativeVersion:'2.1.292',artifactRoot:'/synthetic/artifact',workRoot:'/synthetic/work',inventory,artifactRevision:digest(inventory)};
 const binding={installationId:'installation',databaseName:'synthetic',admissionSchema:'trellis_claude',accountId:'account',accountAlias:'alias',launcherId:'launcher'};
 const windows=[['session','current-session',18000000],['weekly','all-model-weekly',604800000]].map(([windowId,windowClass,durationMs])=>({windowId,windowClass,durationMs,cutoffMs:now+300000,timezone:'America/New_York',rounding:'floor-percent',semanticsRevision:H}));
 const mapping=signed({format:'bowerloom/claude-window-mapping/v1',policyVersion:POLICY_VERSION,epochId:'synthetic-epoch',accountId:'account',accountBindingRevision:H,reviewRevision:H,issuedAtMs:now-1000,expiresAtMs:now+150000,trialDeadlineMs:now+120000,completedResetPolicy:'hold',routes:Object.fromEntries(ROUTES.map(r=>[r,['session','weekly']])),windows});
 const qualification=signed({format:'bowerloom/claude-launch-qualification/v1',receiptId:'qualification',status:'active',nativeSha256:H,nativeVersion:'2.1.292',artifactRevision:host.artifactRevision,accountBindingRevision:H,policyVersion:POLICY_VERSION,environmentRevision:environmentRevision(),wireProfile:'claude-json-unqualified/v1',routes:[...ROUTES],controlsReviewRevision:H,issuedAtMs:now-1000,expiresAtMs:now+150000});
 const task='Produce a synthetic two-line team handoff.';
 const grant=signed({format:'bowerloom/claude-exchange-grant/v1',grantId:'grant',status:'active',operationId:'operation',hostBinding:binding,accountBindingRevision:H,mappingRevision:mapping.revision,qualificationId:qualification.receiptId,qualificationRevision:qualification.revision,artifactRevision:host.artifactRevision,nativePath:host.nativePath,nativeSha256:H,nativeVersion:'2.1.292',runtime:{executable:process.execPath,sha256:H,nodeVersion:'v24.11.0',uvVersion:'1.51.0',platform:'darwin',arch:'arm64'},policyVersion:POLICY_VERSION,roleAssetRevision:digest(roleAssets),taskDigest:byteDigest(task),leadPromptDigest:byteDigest(exchangePrompt(roleAssets,task)),allowances:{lead:{session:2,weekly:2},worker:{session:2,weekly:2}},issuedAtMs:now-1000,expiresAtMs:now+100000,reviewRevision:H,derivation:'claude-one-child/v1'});
 const options={host,roleAssets,admission:new PostgresAdmission(db,{schema:binding.admissionSchema,launcherId:'launcher',controlIdentity:{installationId:'installation',databaseName:'synthetic'}}),fence:{binding,signal:abort.signal,assert(){if(abort.signal.aborted)throw Error('PRIVATE_FENCE');},async guard(){}},async lookupGrant(){stats.lookups++;stats.events.push('grant');return grant;},async lookupQualification(){stats.qualifications++;return qualification;},observer:{readerId:'synthetic-reader',async read(){stats.reads++;stats.events.push('observation');assert.ok(stats.reads<=64,'finite synthetic observation sequence exhausted');const completedAtMs=now-500+stats.reads;assert.ok(completedAtMs<=Date.now()&&Date.now()-completedAtMs<=5000,'synthetic observation must remain past and fresh');stats.observations.push({id:'sample-'+stats.reads,at:completedAtMs});return{mapping,receipt:{format:'bowerloom/claude-ui-receipt/v1',receiptId:'sample-'+stats.reads,readerId:'synthetic-reader',sourceEvidenceSha256:H,accountId:'account',accountBindingRevision:H,capacityLinkRevision:H,authMethod:'claude.ai',apiProvider:'firstParty',subscriptionType:'max',creditsEnabled:false,ordinaryUsageAllowed:true,startedAtMs:completedAtMs-1,completedAtMs,refreshComplete:true,applicabilityComplete:true,applicabilityEvidenceSha256:H,windows:windows.map(w=>({windowId:w.windowId,windowClass:w.windowClass,rawPercent:'0%',displayPercent:0,resetLabels:['Synthetic minute'],timezone:w.timezone,durationMs:w.durationMs,resetLowerMs:now+300000,resetUpperMs:now+360000,refreshComplete:true,conflicting:false,accountedThroughMs:null}))}};},async quiescence(){return{cleanup:'verified'};}}};
 state.measure=async h=>({format:'bowerloom/claude-measurement/v1',nativePath:h.nativePath,nativeSha256:h.nativeSha256,nativeVersion:h.nativeVersion,artifactRevision:h.artifactRevision,inventory:h.inventory,measuredAtMs:Date.now()});state.workspace=async()=>({cwd:'/synthetic/work',async verify(){},async close(){}});
 state.start=async(job)=>{stats.starts++;stats.events.push('start');stats.envelopes.push(job.startup);let ended=false;const done=deferred();return{guardianPid:200+stats.starts,identity:{pid:100+stats.starts,groupId:100+stats.starts,ownershipDigest:H},done:done.promise,write(){stats.writes++;},end(){stats.ends++;ended=true;done.resolve({code:0,reason:null,leaderReaped:true,groupGone:true});},async terminate(){stats.terminates++;if(!ended)done.resolve({code:null,reason:'CANCELLED',leaderReaped:true,groupGone:true});}};};
 state.response=e=>{const high=e.requestedRoute===ROUTES[0];const output=high?{kind:'delegation-proposal',workerRole:'knowledge-library',task:'Summarize the synthetic evidence.',requestedOutput:'Two lines.'}:{kind:'worker-result',parentOutputRevision:e.parentOutputRevision,text:'Synthetic complete.'};return validateResponseEvidence({format:'bowerloom/claude-response-evidence/v1',requestedRoute:e.requestedRoute,requestRevision:e.requestRevision,responseEvidenceSha256:H,localSelection:{model:'claude-sonnet-5-5',effort:high?'high':'medium',nativeVersion:'2.1.292'},effective:{model:'claude-sonnet-5-5',effort:high?'high':'medium',evidenceSha256:H},toolEvents:[],output},{...e,responseEvidenceSha256:H});};
 const input={operationId:'operation',grantId:'grant',grantRevision:grant.revision,syntheticTask:task};return{db,abort,stats,options,grant,qualification,mapping,input,runner:()=>new ClaudeControlledExchange(options)};
}
test('synthetic fixture ordering preserves same-time refusal by real admission',async()=>{
 const f=await setup();let registered=await f.options.observer.read();
 const projector=createObservationProjector({readerId:f.options.observer.readerId,accountId:'account',accountBindingRevision:f.grant.accountBindingRevision,mappingRevision:f.mapping.revision,reviewRevision:f.mapping.reviewRevision},()=>registered,()=>Date.now());
 const first=projector.project(registered.receipt.receiptId).observation,accepted=acceptObservation(f.db.snapshot(),first,Date.now());assert.equal(accepted.accepted,true);
 const sameTime={...structuredClone(first),observationId:'distinct-same-time'};const refused=acceptObservation(accepted.state,sameTime,Date.now());assert.equal(refused.accepted,false);assert.equal(refused.reason,'OUT_OF_ORDER_OBSERVATION');assert.deepEqual(refused.state,accepted.state);
 registered=await f.options.observer.read();const next=projector.project(registered.receipt.receiptId).observation;assert.ok(next.observedAtMs>first.observedAtMs);assert.equal(acceptObservation(accepted.state,next,Date.now()).accepted,true);assert.equal(f.stats.starts,0);assert.equal(f.stats.writes,0);assert.deepEqual(f.db.snapshot().reservations,{});
});
test('real controlled composition completes exactly high then medium; both allowances remain held',async()=>{const f=await setup(),r=f.runner(),out=await r.run(f.input,f.abort.signal);assert.equal(out.protectedEffectsAuthorized,false);assert.deepEqual(out.phases.map(p=>p.modelRoute),ROUTES);assert.equal(f.stats.starts,2);assert.equal(f.stats.terminates,2);assert.ok(f.stats.reads>=8);const rows=Object.values(f.db.snapshot().reservations);assert.equal(rows.length,2);for(const row of rows){assert.equal(row.status,'COMPLETED');assert.equal(row.permitHash,null);assert.equal(row.retained.session.percent,2);assert.equal(row.retained.weekly.percent,2);}assert.equal(rows.reduce((n,r)=>n+r.retained.session.percent,0),4);assert.equal((await r.quiescence()).cleanup,'verified');assert.equal(r.retainedOwners(),0);await assert.rejects(r.run(f.input,f.abort.signal));assert.equal(f.stats.starts,2);});
test('a second controller cannot replay an operation under the durable claim',async()=>{const f=await setup();await f.runner().run(f.input,f.abort.signal);await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,2);});
test('strict effective effort refusal records rejected lead completion and never spawns worker',async()=>{const f=await setup();state.response=()=>{throw Error('CLAUDE_EFFECTIVE_EVIDENCE');};await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,1);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'COMPLETED');assert.equal(Object.values(f.db.snapshot().reservations)[0].retained.session.percent,2);});
test('rehashed task/artifact/host grant drift and nested proxies stop before admission',async()=>{for(const change of [g=>g.taskDigest='b'.repeat(64),g=>g.artifactRevision='b'.repeat(64),g=>g.hostBinding={...g.hostBinding,launcherId:'other'}]){const f=await setup();change(f.grant);const {revision,...body}=f.grant;f.grant.revision=digest(body);f.input.grantRevision=f.grant.revision;await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,0);assert.equal(Object.keys(f.db.snapshot().reservations).length,0);}const f=await setup();let traps=0;f.grant.runtime=new Proxy({},{ownKeys(){traps++;return[];}});await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(traps,0);});
test('lost RUNNING acknowledgement preserves exact claim, reaps owned lead and prevents child',async()=>{const f=await setup();let fired=false;f.db.hook=(sql,v,execute)=>{if(sql==='COMMIT'){const result=execute();if(!fired&&Object.values(f.db.snapshot().reservations).some(r=>r.status==='RUNNING')){fired=true;throw Error('PRIVATE_ACK');}return result;}};const runner=f.runner();await assert.rejects(runner.run(f.input,f.abort.signal),{message:'CLAUDE_LAUNCH_REFUSED'});assert.equal(fired,true);assert.equal(f.stats.starts,1);assert.equal(f.stats.terminates,1);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'RUNNING');await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,1);});
test('cancelled registry retains pending work and observes late rejection without starting',async()=>{const f=await setup(),entered=deferred(),late=deferred();f.options.lookupGrant=()=>{entered.resolve();return late.promise;};const r=f.runner(),running=r.run(f.input,f.abort.signal);await entered.promise;f.abort.abort();await assert.rejects(running);assert.equal(r.lifecycle(),'pending');late.reject(Error('PRIVATE_LATE'));await tick();assert.equal(f.stats.starts,0);assert.equal((await r.quiescence()).cleanup,'unverified');});
test('prehandle cleanup refusal retains actual core after pending promises settle',async()=>{const f=await setup();let openingAttempts=0;state.start=async()=>{openingAttempts++;throw Error('PRIVATE_OPEN');};const r=f.runner();await assert.rejects(r.run(f.input,f.abort.signal));assert.equal(openingAttempts,1,JSON.stringify({boundary:'prehandle-open',observations:f.stats.observations,events:f.stats.events}));assert.equal((await r.quiescence()).cleanup,'unverified');assert.ok(r.retainedOwners()>0);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'LAUNCHING');await assert.rejects(r.run(f.input,f.abort.signal));assert.equal(openingAttempts,1);});
test('every uncertain durable acknowledgement preserves charge and forbids another phase',async()=>{for(const stage of ['RESERVED','LAUNCHING','COMPLETED']){const f=await setup();let fired=false;const commits=[];f.db.hook=(sql,v,execute)=>{if(sql==='COMMIT'){const value=execute(),statuses=Object.values(f.db.snapshot().reservations).map(r=>r.status);commits.push(statuses);if(!fired&&statuses.includes(stage)){fired=true;throw Error('PRIVATE_COMMIT');}return value;}};await assert.rejects(f.runner().run(f.input,f.abort.signal));const detail=JSON.stringify({stage,commits,observations:f.stats.observations,events:f.stats.events});assert.equal(fired,true,detail);assert.equal(f.stats.starts,stage==='COMPLETED'?1:0,detail);const rows=Object.values(f.db.snapshot().reservations);assert.equal(rows.length,1,detail);assert.equal(rows[0].status,stage,detail);assert.equal(rows[0].retained.session.percent,2,detail);await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,stage==='COMPLETED'?1:0,detail);}});
test('concurrent controllers share the stable job namespace; only one exchange can start',async()=>{const f=await setup(),out=await Promise.allSettled([f.runner().run(f.input,f.abort.signal),f.runner().run(f.input,f.abort.signal)]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.stats.starts,2);assert.equal(Object.keys(f.db.snapshot().reservations).length,2);});
test('wrong returned group identity retains LAUNCHING and cleans exact owned handle',async()=>{const f=await setup(),base=state.start;state.start=async(...a)=>{const h=await base(...a);h.identity.groupId++;return h;};await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,1);assert.equal(f.stats.terminates,1);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'LAUNCHING');});
test('observation cancellation after reservation settles late without dispatch or release',async()=>{const f=await setup(),entered=deferred(),late=deferred(),read=f.options.observer.read;let n=0;f.options.observer.read=async()=>{n++;if(n===2){entered.resolve();return late.promise;}return read();};const runner=f.runner(),p=runner.run(f.input,f.abort.signal);await entered.promise;f.abort.abort();await assert.rejects(p);late.reject(Error('PRIVATE_LATE_OBSERVER'));await tick();assert.equal(f.stats.starts,0);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'RESERVED');assert.equal((await runner.quiescence()).cleanup,'unverified');});
test('qualification revocation and unmapped capacity refuse without process launch',async()=>{for(const mode of ['qualification','capacity']){const f=await setup();if(mode==='qualification')f.options.lookupQualification=async()=>({...f.qualification,status:'revoked'});else{const read=f.options.observer.read;f.options.observer.read=async()=>{const v=await read();v.receipt.capacityLinkRevision=null;return v;};}await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,0);assert.equal(Object.keys(f.db.snapshot().reservations).length,0);}});
test('grant or qualification revoked during final measurement/workspace is reread before any consume',async()=>{
 for(const boundary of ['measurement','workspace'])for(const target of ['grant','qualification']){
  const f=await setup();let measures=0,consumes=0,revoked=false;const measure=state.measure;
  const revoke=()=>{revoked=true;f[target].status='revoked';};
  state.measure=async(...args)=>{const value=await measure(...args);if(++measures===3&&boundary==='measurement')revoke();return value;};
  state.workspace=async()=>({cwd:'/synthetic/work',async verify(){if(boundary==='workspace')revoke();},async close(){}});
  const launch=f.options.admission.launchOnceControlled.bind(f.options.admission);
  f.options.admission.launchOnceControlled=(alias,job,permit,observation,start,control)=>launch(alias,job,permit,observation,(request,gate)=>start(request,{check:gate.check,consume(){consumes++;return gate.consume();}}),control);
  await assert.rejects(f.runner().run(f.input,f.abort.signal),{message:'CLAUDE_LAUNCH_REFUSED'});
  assert.equal(revoked,true);assert.equal(consumes,0);assert.equal(f.stats.starts,0);assert.equal(f.stats.writes,0);assert.equal(f.stats.ends,0);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'LAUNCHING');
 }
});
test('initial invalid or throwing host binding sanitizes and settles without abandoning busy state',async()=>{
 for(const mode of ['invalid','throwing']){
  const f=await setup(),original=f.options.fence.binding;
  if(mode==='invalid')f.options.fence.binding={};else Object.defineProperty(f.options.fence,'binding',{configurable:true,get(){throw Error('PRIVATE_BINDING_GETTER');}});
  const runner=f.runner();await assert.rejects(runner.run(f.input,f.abort.signal),{code:'CLAUDE_LAUNCH_REFUSED',message:'CLAUDE_LAUNCH_REFUSED'});
  assert.equal(runner.lifecycle(),'verified');assert.equal(runner.retainedOwners(),0);assert.equal((await runner.quiescence()).cleanup,'verified');assert.equal(f.stats.lookups,0);assert.equal(f.stats.reads,0);assert.equal(f.stats.starts,0);assert.deepEqual(f.db.snapshot().reservations,{});
  Object.defineProperty(f.options.fence,'binding',{configurable:true,writable:true,value:original});
  // Failed entry deliberately consumes this in-memory operation ID; no automatic retry is granted.
  await assert.rejects(runner.run(f.input,f.abort.signal),{code:'CLAUDE_LAUNCH_REFUSED',message:'CLAUDE_LAUNCH_REFUSED'});assert.equal(runner.lifecycle(),'verified');assert.equal(f.stats.lookups,0);
 }
});

async function setupLimited(){
 const f=await setup(),H='a'.repeat(64),now=Date.now();
 const approval=signed({format:'bowerloom/claude-limited-owner-approval/v1',approvalId:'approval',status:'active',proposalSha256:OWNER_PROPOSAL,policyVersion:LIMITED_POLICY,operationId:f.grant.operationId,hostBinding:f.grant.hostBinding,roleAssetRevision:f.grant.roleAssetRevision,taskDigest:f.grant.taskDigest,routes:ROUTES,appliedEffort:'unknown',strictPolicyAccepted:false,ordinaryQualification:false,issuedAtMs:now-1000,expiresAtMs:now+150000});
 const qbody={...f.qualification,format:'bowerloom/claude-limited-launch-qualification/v1',policyVersion:LIMITED_POLICY,environmentRevision:limitedEnvironmentRevision(),wireProfile:LIMITED_WIRE_PROFILE,wireProfileRevision:LIMITED_PROFILE_REVISION,managedInventoryRevision:H,ownerApprovalRevision:approval.revision,runtimeRevision:digest(f.grant.runtime),wireFixtureRevision:H,nativeRetryPolicy:'no-retry-qualified'};delete qbody.revision;Object.assign(f.qualification,signed(qbody));
 const gbody={...f.grant,format:'bowerloom/claude-limited-exchange-grant/v1',policyVersion:LIMITED_POLICY,qualificationRevision:f.qualification.revision,ownerApprovalId:approval.approvalId,ownerApprovalRevision:approval.revision,managedInventoryRevision:H,environmentRevision:limitedEnvironmentRevision(),wireProfileRevision:LIMITED_PROFILE_REVISION,runtimeRevision:digest(f.grant.runtime)};delete gbody.revision;Object.assign(f.grant,signed(gbody));f.input.grantRevision=f.grant.revision;
 f.stats.approvals=0;f.stats.prompts=[];f.options.lookupOwnerApproval=async()=>{f.stats.approvals++;return approval;};
 const original=state.start;state.start=async(job,signal,onChunk)=>{const h=await original(job,signal,onChunk);let prompt='';const write=h.write,end=h.end;h.write=text=>{prompt=text;f.stats.prompts.push(text);write(text);};h.end=()=>{
  const parent=/PARENT OUTPUT ([a-f0-9]{64}):/.exec(prompt)?.[1],output=parent?{kind:'worker-result',parentOutputRevision:parent,text:'Synthetic worker complete.'}:{kind:'delegation-proposal',workerRole:'knowledge-library',task:'Synthetic handoff',requestedOutput:'One line.'},text=JSON.stringify(output),session='session-'+f.stats.starts;
  const frames=[{type:'system',subtype:'init',session_id:session,model:'claude-sonnet-5-5',tools:[],mcp_servers:[]},{type:'assistant',message:{id:'message-'+f.stats.starts,type:'message',role:'assistant',model:'claude-sonnet-5-5',content:[{type:'text',text}],stop_reason:'end_turn',stop_sequence:null,usage:{}},parent_tool_use_id:null,session_id:session,uuid:'assistant-'+f.stats.starts,request_id:'request-'+f.stats.starts},{type:'result',subtype:'success',is_error:false,num_turns:1,result:text,stop_reason:'end_turn',permission_denials:[],uuid:'result-'+f.stats.starts,session_id:session}];
  f.mutateFrames?.(frames);onChunk('stdout',Buffer.from(frames.map(JSON.stringify).join('\n')+'\n'));end();};return h;};
 f.approval=approval;f.runner=()=>new LimitedClaudeControlledExchange(f.options);return f;
}
test('limited actual core and fixed candidate decoder complete causal high→medium with unknown applied effort',async()=>{
 const f=await setupLimited(),runner=f.runner(),out=await runner.run(f.input,f.abort.signal);assert.equal(out.format,'bowerloom/claude-limited-exchange/v1');assert.equal(out.appliedEffort,'unknown');assert.equal(out.strictPolicyAccepted,false);assert.equal(out.ordinaryQualification,false);assert.equal(f.stats.starts,2);assert.ok(f.stats.approvals>=f.stats.reads);assert.deepEqual(out.phases.map(p=>p.modelRoute),ROUTES);
 for(const p of out.phases){assert.equal(p.responseReceipt.provider.model,'claude-sonnet-5-5');assert.equal(p.responseReceipt.appliedEffort,'unknown');assert.equal(p.responseReceipt.strictPolicyAccepted,false);assert.equal(p.responseReceipt.requestRevision,p.requestRevision.slice(7));}
 assert.equal(out.phases[1].responseReceipt.parentOutputRevision,out.phases[0].outputRevision);assert.ok(f.stats.prompts[0].includes(f.options.roleAssets.techLead));assert.ok(f.stats.prompts[1].includes(f.options.roleAssets.knowledgeLibrary));assert.ok(f.stats.prompts[1].includes(out.phases[0].outputRevision));
 for(const row of Object.values(f.db.snapshot().reservations)){assert.equal(row.status,'COMPLETED');assert.equal(row.retained.session.percent,2);assert.equal(row.retained.weekly.percent,2);}assert.equal((await runner.quiescence()).cleanup,'verified');assert.equal(runner.retainedOwners(),0);await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,2);
});
test('strict constructor refuses limited options/grants; stable jobs prevent policy-switch replay',async()=>{
 const f=await setupLimited();assert.throws(()=>new ClaudeControlledExchange(f.options));const strictOptions={...f.options};delete strictOptions.lookupOwnerApproval;await assert.rejects(new ClaudeControlledExchange(strictOptions).run(f.input,f.abort.signal));assert.equal(f.stats.starts,0);
 await f.runner().run(f.input,f.abort.signal);const {ownerApprovalId,ownerApprovalRevision,managedInventoryRevision,environmentRevision:env,wireProfileRevision,runtimeRevision,revision,...body}=f.grant;
 const strict=signed({...body,format:'bowerloom/claude-exchange-grant/v1',policyVersion:POLICY_VERSION});const q={...f.qualification};for(const k of ['wireProfileRevision','managedInventoryRevision','ownerApprovalRevision','runtimeRevision','wireFixtureRevision','nativeRetryPolicy','revision'])delete q[k];Object.assign(q,{format:'bowerloom/claude-launch-qualification/v1',policyVersion:POLICY_VERSION,environmentRevision:environmentRevision(),wireProfile:'claude-json-unqualified/v1'});const strictQ=signed(q);const {revision:unused,...sg}=strict;const strictG=signed({...sg,qualificationRevision:strictQ.revision});strictOptions.lookupGrant=async()=>strictG;strictOptions.lookupQualification=async()=>strictQ;
 await assert.rejects(new ClaudeControlledExchange(strictOptions).run({...f.input,grantRevision:strictG.revision},f.abort.signal));assert.equal(f.stats.starts,2);assert.equal(Object.keys(f.db.snapshot().reservations).length,2);
});
test('limited approval/qualification drift stops before admission and final host-await revocation stops consume',async()=>{
 for(const mode of ['owner','managed','environment','artifact','fixture']){const f=await setupLimited();if(mode==='owner')f.approval.status='revoked';else f.qualification[({managed:'managedInventoryRevision',environment:'environmentRevision',artifact:'artifactRevision',fixture:'wireFixtureRevision'})[mode]]='b'.repeat(64);await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(f.stats.starts,0);assert.equal(f.stats.reads,0);assert.deepEqual(f.db.snapshot().reservations,{});}
 for(const boundary of ['measure','workspace']){const f=await setupLimited(),measure=state.measure;let n=0,consumes=0;state.measure=async(...args)=>{const value=await measure(...args);if(++n===3&&boundary==='measure')f.approval.status='revoked';return value;};state.workspace=async()=>({cwd:'/synthetic/work',async verify(){if(boundary==='workspace')f.approval.status='revoked';},async close(){}});const launch=f.options.admission.launchOnceControlled.bind(f.options.admission);f.options.admission.launchOnceControlled=(a,j,p,o,start,c)=>launch(a,j,p,o,(r,g)=>start(r,{check:g.check,consume(){consumes++;return g.consume();}}),c);await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(consumes,0);assert.equal(f.stats.starts,0);assert.equal(f.stats.writes,0);assert.equal(Object.values(f.db.snapshot().reservations)[0].status,'LAUNCHING');}
});
test('limited wrong model and retry/tool indications reject charged lead and never spawn worker',async()=>{for(const [name,mutate] of [['wrong-model',f=>f[1].message.model='alias'],['virtual',f=>f[1].is_virtual=true],['retry',f=>f[2].retry_count=1],['tool',f=>f[1].message.content=[{type:'tool_use'}]]]){const f=await setupLimited();let mutations=0;f.mutateFrames=frames=>{mutations++;mutate(frames);};await assert.rejects(f.runner().run(f.input,f.abort.signal));const detail=JSON.stringify({name,mutations,observations:f.stats.observations,events:f.stats.events});assert.equal(f.stats.starts,1,detail);assert.equal(mutations,1,detail);assert.equal(f.stats.terminates,1,detail);const row=Object.values(f.db.snapshot().reservations)[0];assert.equal(row.status,'COMPLETED',detail);assert.equal(row.retained.session.percent,2,detail);}});
test('limited lost acknowledgement, pending cancellation and prehandle cleanup uncertainty retain ownership/charges',async()=>{
 for(const stage of ['RESERVED','LAUNCHING','RUNNING','COMPLETED']){const f=await setupLimited();let fired=false;f.db.hook=(sql,v,execute)=>{if(sql==='COMMIT'){const out=execute();if(!fired&&Object.values(f.db.snapshot().reservations).some(r=>r.status===stage)){fired=true;throw Error('PRIVATE_LOST_ACK');}return out;}};await assert.rejects(f.runner().run(f.input,f.abort.signal));assert.equal(fired,true);assert.equal(f.stats.starts,['RUNNING','COMPLETED'].includes(stage)?1:0);const row=Object.values(f.db.snapshot().reservations)[0];assert.equal(row.status,stage);assert.equal(row.retained.session.percent,2);}
 const f=await setupLimited(),entered=deferred(),late=deferred();f.options.lookupOwnerApproval=()=>{entered.resolve();return late.promise;};const runner=f.runner(),run=runner.run(f.input,f.abort.signal);await entered.promise;f.abort.abort();await assert.rejects(run);late.reject(Error('PRIVATE_LATE'));await tick();assert.equal(f.stats.starts,0);assert.equal((await runner.quiescence()).cleanup,'unverified');
 const g=await setupLimited();state.start=async()=>{throw Error('PRIVATE_NO_HANDLE');};const r=g.runner();await assert.rejects(r.run(g.input,g.abort.signal));assert.equal((await r.quiescence()).cleanup,'unverified');assert.ok(r.retainedOwners()>0);assert.equal(Object.values(g.db.snapshot().reservations)[0].status,'LAUNCHING');
});
