import test from 'node:test';import assert from 'node:assert/strict';
import {captureHost,measureHost,candidateEnvironment,environmentRevision} from '../../../dist/packages/claude-adapter/src/host.js';
import {digest} from '../../../dist/packages/claude-adapter/src/policy.js';
const names=['policy','observation','protocol','installation','boundary','host','wire','adapter-core','controlled-exchange','limited-policy','limited-protocol','limited-wire'].map(n=>`dist/packages/claude-adapter/src/${n}.js`).concat(['startup-deadline','supervisor','guardian','safe','policy'].map(n=>`dist/packages/codex-adapter/src/${n}.js`),['dist/packages/mcp-connections/src/darwin-boot-session.js','dist/packages/mcp-connections/src/model.js','dist/packages/contracts/src/index.js']);
function host(){const inventory=names.sort().map(path=>({path,sha256:'a'.repeat(64),bytes:1}));return{nativePath:'/synthetic/claude',nativeSha256:'a'.repeat(64),nativeVersion:'2.1.292',artifactRoot:'/synthetic/artifact',workRoot:'/synthetic/work',inventory,artifactRevision:digest(inventory)};}
test('closure is immutable and requires every actual local transitive entry',()=>{const h=host(),out=captureHost(h);h.inventory.pop();assert.equal(out.inventory.length,names.length);assert.ok(Object.isFrozen(out.inventory));for(const path of names){const f=host();f.inventory=f.inventory.filter(r=>r.path!==path);f.artifactRevision=digest(f.inventory);assert.throws(()=>captureHost(f));}});
test('duplicate traversal byte drift and unknown native versions refuse',()=>{for(const change of [h=>h.inventory[0].path='../private',h=>h.inventory.push(h.inventory[0]),h=>h.inventory[0].bytes++,h=>h.nativeVersion='2.1.293']){const h=host();change(h);assert.throws(()=>captureHost(h));}});
test('preabort reaches no actual filesystem/native measurement',async()=>{const c=new AbortController();c.abort();await assert.rejects(measureHost(host(),c.signal),{message:'CLAUDE_LAUNCH_REFUSED'});});
test('candidate environment is fixed does not inherit authentication and is explicitly separately qualified',()=>{const e=candidateEnvironment();assert.deepEqual(e,{DISABLE_UPDATES:'1',LANG:'C'});e.ANTHROPIC_API_KEY='synthetic';assert.equal(candidateEnvironment().ANTHROPIC_API_KEY,undefined);assert.match(environmentRevision(),/^[a-f0-9]{64}$/);});
