// SYNTHETIC normalized evidence; hashes alone are not native provenance.
import test from 'node:test';import assert from 'node:assert/strict';
import {digest,ROUTES} from '../../../dist/packages/claude-adapter/src/policy.js';
import {validateResponseEvidence} from '../../../dist/packages/claude-adapter/src/protocol.js';
import {LIMITED_POLICY,LIMITED_PROFILE_REVISION} from '../../../dist/packages/claude-adapter/src/limited-policy.js';
import {validateLimitedResponse} from '../../../dist/packages/claude-adapter/src/limited-protocol.js';
const H='a'.repeat(64),signed=b=>({...b,revision:digest(b)});
function fixture(worker=false){const e={requestedRoute:ROUTES[worker?1:0],requestRevision:H,parentOutputRevision:worker?H:null,launchPlanRevision:H,qualificationRevision:H,ownerApprovalRevision:H},body={format:'bowerloom/claude-limited-response/v1',policyVersion:LIMITED_POLICY,...e,wireProfileRevision:LIMITED_PROFILE_REVISION,requested:{model:'claude-sonnet-5-5',effort:worker?'medium':'high',nativeVersion:'2.1.292'},provider:{model:'claude-sonnet-5-5',sessionId:'session',messageId:'message',requestId:'request',responseEvidenceSha256:H},output:worker?{kind:'worker-result',parentOutputRevision:H,text:'Synthetic result'}:{kind:'delegation-proposal',workerRole:'knowledge-library',task:'Synthetic task',requestedOutput:'A line'},appliedEffort:'unknown',strictPolicyAccepted:false,ordinaryQualification:false,retainedChargesMustRemain:true};return{e,body,v:signed(body)};}
test('limited receipt preserves unknown effort and causal worker output under exact bindings',()=>{for(const worker of [false,true]){const {v,e}=fixture(worker),r=validateLimitedResponse(v,e);assert.equal(r.appliedEffort,'unknown');assert.equal(r.strictPolicyAccepted,false);assert.equal(r.ordinaryQualification,false);assert.equal(r.retainedChargesMustRemain,true);assert.throws(()=>validateResponseEvidence(v,{...e,responseEvidenceSha256:H}));}});
test('request/model/status cannot supply effective effort; wrong provider or owner/request/parent rejects',()=>{for(const key of ['appliedEffort','strictPolicyAccepted','ordinaryQualification','ownerApprovalRevision','requestRevision']){const {e,body}=fixture();const value=key==='appliedEffort'?'high':key.endsWith('Revision')?'b'.repeat(64):true;assert.throws(()=>validateLimitedResponse(signed({...body,[key]:value}),e));}const {e,body}=fixture(true);assert.throws(()=>validateLimitedResponse(signed({...body,output:{...body.output,parentOutputRevision:'b'.repeat(64)}}),e));assert.throws(()=>validateLimitedResponse(signed({...body,provider:{...body.provider,model:'claude-sonnet-alias'}}),e));assert.throws(()=>validateLimitedResponse(signed({...body,effective:{effort:'medium'}}),e));});
test('a genuinely validated strict receipt cannot be relabeled as limited',()=>{const {e,body}=fixture();const v={format:'bowerloom/claude-response-evidence/v1',requestedRoute:e.requestedRoute,requestRevision:H,responseEvidenceSha256:H,localSelection:{model:'claude-sonnet-5-5',effort:'high',nativeVersion:'2.1.292'},effective:{model:'claude-sonnet-5-5',effort:'high',evidenceSha256:H},toolEvents:[],output:body.output};const strict=validateResponseEvidence(v,{requestedRoute:e.requestedRoute,requestRevision:H,responseEvidenceSha256:H,parentOutputRevision:null});assert.throws(()=>validateLimitedResponse(strict,e));assert.throws(()=>validateLimitedResponse(v,e));});
