// SYNTHETIC registry assertions only; no actual controls, account, provider or native qualification.
import test from 'node:test';import assert from 'node:assert/strict';
import {digest,ROUTES,POLICY_VERSION} from '../../../dist/packages/claude-adapter/src/policy.js';
import {captureGrant,captureQualification} from '../../../dist/packages/claude-adapter/src/boundary.js';
import {LIMITED_POLICY,LIMITED_PROFILE_REVISION,OWNER_PROPOSAL,LIMITED_WIRE_PROFILE,limitedEnvironmentRevision,captureLimitedGrant,captureLimitedOwnerApproval,captureLimitedQualification,prepareLimitedInstallation,limitedArgv} from '../../../dist/packages/claude-adapter/src/limited-policy.js';
const H='a'.repeat(64),signed=b=>({...b,revision:digest(b)});
function fixture(){const hostBinding={installationId:'i',databaseName:'d',admissionSchema:'a',accountId:'u',accountAlias:'u',launcherId:'l'},runtime={executable:'/synthetic/node',sha256:H,nodeVersion:'v24.11.0',uvVersion:'1.51.0',platform:'darwin',arch:'arm64'};
 const a=signed({format:'bowerloom/claude-limited-owner-approval/v1',approvalId:'approval',status:'active',proposalSha256:OWNER_PROPOSAL,policyVersion:LIMITED_POLICY,operationId:'op',hostBinding,roleAssetRevision:H,taskDigest:H,routes:ROUTES,appliedEffort:'unknown',strictPolicyAccepted:false,ordinaryQualification:false,issuedAtMs:1000,expiresAtMs:9000});
 const q=signed({format:'bowerloom/claude-limited-launch-qualification/v1',receiptId:'q',status:'active',nativeSha256:H,nativeVersion:'2.1.292',artifactRevision:H,accountBindingRevision:H,policyVersion:LIMITED_POLICY,environmentRevision:limitedEnvironmentRevision(),wireProfile:LIMITED_WIRE_PROFILE,wireProfileRevision:LIMITED_PROFILE_REVISION,routes:ROUTES,controlsReviewRevision:H,wireFixtureRevision:H,managedInventoryRevision:H,ownerApprovalRevision:a.revision,runtimeRevision:digest(runtime),nativeRetryPolicy:'no-retry-qualified',issuedAtMs:1000,expiresAtMs:9000});
 const g=signed({format:'bowerloom/claude-limited-exchange-grant/v1',grantId:'g',status:'active',operationId:'op',hostBinding,accountBindingRevision:H,mappingRevision:H,qualificationId:'q',qualificationRevision:q.revision,artifactRevision:H,nativePath:'/synthetic/claude',nativeSha256:H,nativeVersion:'2.1.292',runtime,runtimeRevision:digest(runtime),policyVersion:LIMITED_POLICY,roleAssetRevision:H,taskDigest:H,leadPromptDigest:H,allowances:{lead:{weekly:2},worker:{weekly:2}},issuedAtMs:1000,expiresAtMs:8000,reviewRevision:H,derivation:'claude-one-child/v1',ownerApprovalId:a.approvalId,ownerApprovalRevision:a.revision,managedInventoryRevision:H,environmentRevision:limitedEnvironmentRevision(),wireProfileRevision:LIMITED_PROFILE_REVISION});return{g,q,a};}
test('limited registry contracts require independently supplied approval and exact qualification pins',()=>{const {g,q,a}=fixture();assert.equal(captureLimitedGrant(g).policyVersion,LIMITED_POLICY);assert.equal(captureLimitedOwnerApproval(a,g,2000).appliedEffort,'unknown');assert.equal(captureLimitedQualification(q,g,2000).nativeRetryPolicy,'no-retry-qualified');for(const k of ['managedInventoryRevision','environmentRevision','wireProfileRevision','runtimeRevision','ownerApprovalRevision','artifactRevision']){const changed={...q,[k]:'b'.repeat(64)};delete changed.revision;const mutated=signed(changed);assert.throws(()=>captureLimitedQualification(mutated,{...g,qualificationRevision:mutated.revision},2000));}});
test('strict/limited identities cannot cross; local signed approval is not sufficient without exact registry binding',()=>{const {g,q,a}=fixture();assert.throws(()=>captureGrant(g));assert.throws(()=>captureQualification(q,g,2000));for(const change of [{proposalSha256:H},{operationId:'other'},{appliedEffort:'high'},{strictPolicyAccepted:true},{expiresAtMs:7000}]){const {revision,...body}=a,mutated=signed({...body,...change});assert.throws(()=>captureLimitedOwnerApproval(mutated,{...g,ownerApprovalRevision:mutated.revision},2000));}const {revision,...body}=g;assert.throws(()=>captureLimitedGrant(signed({...body,policyVersion:POLICY_VERSION})));assert.throws(()=>captureLimitedGrant(signed({...body,runtimeRevision:'b'.repeat(64)})));});
test('capture refuses proxies/accessors without traps and freezes complete nested authority',()=>{const {g}=fixture();let traps=0;assert.throws(()=>captureLimitedGrant(new Proxy(g,{ownKeys(){traps++;return[];}})));const hostile={...g};Object.defineProperty(hostile,'runtime',{enumerable:true,get(){traps++;return{};}});assert.throws(()=>captureLimitedGrant(hostile));assert.equal(traps,0);const saved=captureLimitedGrant(g);g.allowances.lead.weekly=99;assert.equal(saved.allowances.lead.weekly,2);assert.ok(Object.isFrozen(saved.runtime));});
test('limited invocation has distinct verbose stream contract, no fallback and no controls qualification claim',()=>{const inventory=[{path:'dist/synthetic.js',sha256:H,bytes:1}],m={format:'bowerloom/claude-measurement/v1',nativePath:'/synthetic/claude',nativeSha256:H,nativeVersion:'2.1.292',artifactRevision:digest(inventory),inventory,measuredAtMs:2000},e={nativePath:m.nativePath,nativeSha256:H,nativeVersion:m.nativeVersion,artifactRevision:m.artifactRevision};for(const route of ROUTES){const p=prepareLimitedInstallation(m,e,{route,promptSchema:'bowerloom/claude-finite-request/v1',prompt:'Synthetic only',issuedAtMs:1000,expiresAtMs:4000},2000);assert.deepEqual(p.argv,limitedArgv(route));assert.equal(p.argv[p.argv.indexOf('--output-format')+1],'stream-json');assert.ok(p.argv.includes('--verbose'));assert.equal(p.appliedEffort,'unknown');assert.equal(p.controlsQualified,false);assert.equal(p.executionAuthorized,false);assert.equal(p.paidFallback,false);}assert.throws(()=>limitedArgv('claude:claude-sonnet-5-5:low'));});
