// Explicit synthetic candidate stream; no observed native response fixture or qualification.
import test from 'node:test';import assert from 'node:assert/strict';
import {LimitedClaudeWire} from '../../../dist/packages/claude-adapter/src/limited-wire.js';
import {ClaudeWire} from '../../../dist/packages/claude-adapter/src/wire.js';
import {ROUTES} from '../../../dist/packages/claude-adapter/src/policy.js';
const H='a'.repeat(64),e={requestedRoute:ROUTES[0],requestRevision:H,parentOutputRevision:null,launchPlanRevision:H,qualificationRevision:H,ownerApprovalRevision:H};
function frames(){const text=JSON.stringify({kind:'delegation-proposal',workerRole:'knowledge-library',task:'Synthetic only',requestedOutput:'One line'});return[{type:'system',subtype:'init',session_id:'session',model:'claude-sonnet-5-5',tools:[],mcp_servers:[]},{type:'assistant',message:{id:'message',type:'message',role:'assistant',model:'claude-sonnet-5-5',content:[{type:'text',text}],stop_reason:'end_turn',stop_sequence:null,usage:{}},parent_tool_use_id:null,session_id:'session',uuid:'assistant-id',request_id:'request-id'},{type:'result',subtype:'success',is_error:false,num_turns:1,result:text,stop_reason:'end_turn',permission_denials:[],uuid:'result-id',session_id:'session'}];}
function bytes(f){return Buffer.from(f.map(JSON.stringify).join('\n')+'\n');}
test('fixed limited stream preserves provider model and unknown effort; strict decoder still refuses',()=>{const b=bytes(frames()),w=new LimitedClaudeWire();for(let i=0;i<b.length;i+=7)w.feed(b.subarray(i,i+7));const r=w.finish(e);assert.equal(r.provider.model,'claude-sonnet-5-5');assert.equal(r.appliedEffort,'unknown');assert.equal(r.requested.effort,'high');assert.throws(()=>w.finish(e));const strict=new ClaudeWire();strict.feed(Buffer.from('{}'));assert.throws(()=>strict.finish(e),{code:'EFFECTIVE_EVIDENCE'});});
test('wrong provider/local/replayed/tool/fallback/retry/extra-finality indications fail closed',()=>{const changes=[f=>f[1].message.model='alias',f=>delete f[1].request_id,f=>f[1].historical=true,f=>f[1].is_virtual=true,f=>f[1].supersedes=['old'],f=>f[1].message.content=[{type:'tool_use',id:'tool'}],f=>f[1].parent_tool_use_id='parent',f=>f[2].session_id='other',f=>f[2].num_turns=2,f=>f[2].subtype='error_max_turns',f=>f[2].result='{}',f=>f[2].retry_count=1,f=>f[2].fallback_model='alias',f=>f.push(f[2]),f=>f[0].tools=['Read'],f=>f[0].plugins=['plugin']];for(const change of changes){const f=frames();change(f);const w=new LimitedClaudeWire();w.feed(bytes(f));assert.throws(()=>w.finish(e));}});
test('raw byte limits, invalid UTF8 and duplicate JSON keys refuse without normalization',()=>{for(const b of [Buffer.from([0xff]),Buffer.from('\uFEFF'+bytes(frames()).toString()),Buffer.from(bytes(frames()).toString().replace('"subtype":"init"','"subtype":"init","subtype":"init"'))]){const w=new LimitedClaudeWire();w.feed(b);assert.throws(()=>w.finish(e));}const w=new LimitedClaudeWire();assert.throws(()=>w.feed(Buffer.alloc(65537)));});
