import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {MODEL_ROUTE} from '../../../dist/packages/codex-adapter/src/policy.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const tick=()=>new Promise(r=>setImmediate(r));
const key='bowerloom.observer.lifecycle-fixture';let ctx;
function setup(){ctx={checks:0,workspaces:0,closes:0,opens:0,terminates:0,writes:0,native:0,entered:deferred(),done:deferred()};globalThis[key]=ctx;ctx.installationChecks=async()=>{ctx.checks++;if(ctx.prep)await ctx.prep.promise;return{};};ctx.workspace=async()=>{ctx.workspaces++;if(ctx.workspaceWait)await ctx.workspaceWait.promise;return{directory:'/fixture',cwd:'/fixture/work',schema:'/fixture/schema',verify:async()=>{},close:async()=>{ctx.closes++;if(ctx.closeFail)throw Error('PRIVATE_CLOSE');}};};ctx.startGuardian=async(options,signal,onData)=>{ctx.opens++;if(options.argv.includes('exec'))ctx.native++;ctx.signal=signal;ctx.entered.resolve();if(ctx.openWait)await ctx.openWait.promise;return{identity:{ownershipDigest:'a'.repeat(64),pid:1,groupId:1},done:ctx.done.promise,write(text){ctx.writes++;ctx.onWrite?.(JSON.parse(text),onData);},end(){},async terminate(){ctx.terminates++;ctx.done.resolve({code:0,reason:null,leaderReaped:true,groupGone:true});if(ctx.terminateFail)throw Error('PRIVATE_TERMINATE');}};};return ctx;}
const installation='data:text/javascript,'+encodeURIComponent(`const c=()=>globalThis['${key}'];export const installationChecks=(...a)=>c().installationChecks(...a);export const workspace=(...a)=>c().workspace(...a);export const childEnvironment=()=>({});export const execArgs=()=>['exec'];`);
const supervisor='data:text/javascript,'+encodeURIComponent(`export const startGuardian=(...a)=>globalThis['${key}'].startGuardian(...a);`);
const hook=registerHooks({resolve(s,c,next){if(c.parentURL?.match(/\/(reader|adapter-core)\.js$/)){if(s==='./installation.js')return{url:installation,shortCircuit:true};if(s==='./supervisor.js')return{url:supervisor,shortCircuit:true};}return next(s,c);}});
const {CodexObservationReader}=await import('../../../dist/packages/codex-adapter/src/reader.js');
const {CodexAdapterCore}=await import('../../../dist/packages/codex-adapter/src/adapter-core.js');hook.deregister();
const install={nativePath:'/fixture/native',nativeSha256:'ad0be20d04e2ba6146ecdb51d7f8b7b0fe15420a15dc9b0057518d858f1f3714',version:'0.157.0',workRoot:'/fixture'};
const binding={canonicalAccountId:'account',aliases:['alias'],providerAccountSha256:'a'.repeat(64),requiredWindows:['primary'],optionalWindows:['secondary']};
const reader=()=>new CodexObservationReader(install,binding);
const rejection=p=>{const observed=Promise.resolve().then(()=>p()).then(()=>null,e=>e);return observed;};
test('reader pre-abort performs no preparation or opening',async()=>{const c=setup(),r=reader(),a=new AbortController();a.abort();await assert.rejects(r.read('alias',a.signal));assert.equal(c.checks,0);assert.equal(c.opens,0);assert.deepEqual(await r.quiescence(),{cleanup:'verified'});});
for(const phase of ['prep','workspaceWait','openWait'])test('reader cancellation during '+phase+' retains late successful cleanup',async()=>{const c=setup();c[phase]=deferred();const r=reader(),a=new AbortController(),p=rejection(()=>r.read('alias',a.signal));await tick();a.abort();assert.equal(r.cleanupStatus(),'pending');let settled=false;const quiet=r.quiescence().then(v=>{settled=true;return v;});await tick();assert.equal(settled,false);c[phase].resolve();assert.ok(await p);assert.deepEqual(await quiet,{cleanup:'verified'});assert.equal(c.native,0);assert.equal(c.opens,phase==='openWait'?1:0);assert.equal(c.terminates,phase==='openWait'?1:0);assert.equal(c.closes,phase==='prep'?0:1);});
test('reader pending RPC receives operation cancellation and owned termination',async()=>{const c=setup(),r=reader(),a=new AbortController(),p=rejection(()=>r.read('alias',a.signal));await c.entered.promise;await tick();assert.equal(c.writes,1);a.abort();assert.ok(await p);assert.equal(c.signal.aborted,true);assert.equal(c.terminates,1);assert.equal(c.closes,1);assert.deepEqual(await r.quiescence(),{cleanup:'verified'});});
for(const phase of ['workspaceWait','openWait'])test('late '+phase+' rejection remains quarantined and unverified',async()=>{const c=setup();c[phase]=deferred();const r=reader(),a=new AbortController(),p=rejection(()=>r.read('alias',a.signal));await tick();a.abort();c[phase].reject(Error('PRIVATE_LATE'));assert.ok(await p);assert.deepEqual(await r.quiescence(),{cleanup:'unverified'});await assert.rejects(r.read('alias'));assert.equal(c.native,0);});
for(const failure of ['terminateFail','closeFail'])test('reader '+failure+' cannot report verified cleanup or reopen',async()=>{const c=setup();c[failure]=true;const r=reader(),a=new AbortController(),p=rejection(()=>r.read('alias',a.signal));await c.entered.promise;await tick();a.abort();assert.ok(await p);assert.deepEqual(await r.quiescence(),{cleanup:'unverified'});await assert.rejects(r.read('alias'));});
test('core retains internal observer and entire no-handle start on cancellation',async()=>{const c=setup();c.openWait=deferred();const core=new CodexAdapterCore({installation:install,binding,accountAlias:'alias'}),a=new AbortController();const p=rejection(()=>core.start({launcherId:'launcher',taskInput:'synthetic',modelRoute:MODEL_ROUTE},a.signal));await c.entered.promise;a.abort();assert.equal(core.cleanupStatus(),'pending');let settled=false;const quiet=core.quiescence().then(v=>{settled=true;return v;});await tick();assert.equal(settled,false);c.openWait.resolve();assert.ok(await p);assert.deepEqual(await quiet,{cleanup:'verified'});assert.equal(c.native,0);assert.equal(c.terminates,1);assert.equal(c.closes,2);});
test('core no-handle late observer rejection remains unverified and no native start follows',async()=>{const c=setup();c.openWait=deferred();const core=new CodexAdapterCore({installation:install,binding,accountAlias:'alias'}),a=new AbortController();const p=rejection(()=>core.start({launcherId:'launcher',taskInput:'synthetic',modelRoute:MODEL_ROUTE},a.signal));await c.entered.promise;a.abort();c.openWait.reject(Error('PRIVATE_OPEN'));assert.ok(await p);assert.deepEqual(await core.quiescence(),{cleanup:'unverified'});await assert.rejects(core.start({launcherId:'launcher',taskInput:'again',modelRoute:MODEL_ROUTE},new AbortController().signal));assert.equal(c.native,0);});

test('abort after initialize response forbids queued initialized notification',async()=>{const c=setup(),r=reader(),a=new AbortController();c.onWrite=(msg,onData)=>{onData('stdout',Buffer.from(JSON.stringify({id:msg.id,result:{}})+'\n'));a.abort();};await assert.rejects(r.read('alias',a.signal));assert.equal(c.writes,1);assert.equal(c.terminates,1);assert.deepEqual(await r.quiescence(),{cleanup:'verified'});});
test('legacy reader call without signal remains asynchronous and cleans RPC refusal',async()=>{const c=setup(),r=reader();c.onWrite=(msg,onData)=>onData('stdout',Buffer.from(JSON.stringify({id:msg.id,error:{code:1}})+'\n'));await assert.rejects(r.read('alias'));assert.equal(c.writes,1);assert.equal(c.terminates,1);assert.deepEqual(await r.quiescence(),{cleanup:'verified'});});
