// Versioned metaharness policy. Machine paths and account bindings are controller inputs.
export const POLICY_VERSION = 'codex-subscription-proposal/v0.7-alpha.2';
export const CODEX_VERSION = '0.157.0';
export const MODEL_ROUTE = 'codex:gpt-5.5:low';
export const MODEL = 'gpt-5.5';
export const EFFORT = 'low';
export const SUPPORTED_NATIVE_SHA256 = 'ad0be20d04e2ba6146ecdb51d7f8b7b0fe15420a15dc9b0057518d858f1f3714';
export const LIMITS = Object.freeze({ seconds: 60, stdoutBytes: 65536, stderrBytes: 32768, events: 64,
  inputBytes: 32768, observerBytes: 2 * 1024 * 1024, observationAgeMs: 30000, reserveBytes: 12 * 2 ** 30 });
export const CONTROLS: readonly string[] = Object.freeze([
  "--disable",
  "plugins",
  "--disable",
  "remote_plugin",
  "--disable",
  "plugin_sharing",
  "--disable",
  "recommended_plugins",
  "--disable",
  "hooks",
  "--disable",
  "apps",
  "--disable",
  "enable_mcp_apps",
  "--disable",
  "codex_apps_mcp_2026_07_28",
  "--disable",
  "browser_use",
  "--disable",
  "browser_use_external",
  "--disable",
  "browser_use_full_cdp_access",
  "--disable",
  "computer_use",
  "--disable",
  "in_app_browser",
  "--disable",
  "workspace_dependencies",
  "--disable",
  "multi_agent",
  "--disable",
  "multi_agent_v2",
  "--disable",
  "agent_message_board",
  "--disable",
  "memories",
  "--disable",
  "chronicle",
  "--disable",
  "external_agent_memory_import",
  "--disable",
  "shell_snapshot",
  "--disable",
  "shell_snapshot_v2",
  "--disable",
  "shell_tool",
  "--disable",
  "unified_exec",
  "--disable",
  "unified_exec_tty",
  "--disable",
  "code_mode",
  "--disable",
  "code_mode_host",
  "--disable",
  "code_mode_only",
  "--disable",
  "code_mode_prewarm",
  "--disable",
  "image_generation",
  "--disable",
  "view_image",
  "--disable",
  "goals",
  "--disable",
  "skill_search",
  "--disable",
  "skill_mcp_dependency_install",
  "--disable",
  "tool_suggest",
  "--disable",
  "auth_elicitation",
  "--disable",
  "daemon_auto_start",
  "--disable",
  "standalone_web_search",
  "--disable",
  "realtime_conversation",
  "--disable",
  "request_permissions_tool",
  "--enable",
  "skip_host_skill_discovery",
  "-c",
  "agents.enabled=false",
  "-c",
  "skills.bundled.enabled=false",
  "-c",
  "skills.include_instructions=false",
  "-c",
  "project_doc_max_bytes=0",
  "-c",
  "project_doc_fallback_filenames=[]",
  "-c",
  "allow_login_shell=false",
  "-c",
  "shell_environment_policy.inherit=\"none\"",
  "-c",
  "shell_environment_policy.experimental_use_profile=false",
  "-c",
  "web_search=\"disabled\"",
  "-c",
  "analytics.enabled=false",
  "-c",
  "history.persistence=\"none\"",
  "-c",
  "model_provider=\"openai\"",
  "-c",
  "forced_login_method=\"chatgpt\"",
  "-c",
  "suppress_unstable_features_warning=true"
]);
export const RPC_METHODS: readonly string[] = Object.freeze(['initialize','config/read','configRequirements/read',
  'environment/status','account/read','model/list','account/rateLimits/read']);
export const INPUT_KEYS = ['instructions','developer_instructions','base_instructions','model_instructions_file',
  'experimental_instructions_file','compact_prompt','experimental_compact_prompt_file'];
export const ROUTE_KEYS = ['openai_base_url','chatgpt_base_url','model_providers','forced_chatgpt_workspace_id',
  'experimental_realtime_ws_base_url','experimental_realtime_webrtc_call_base_url','model_catalog_json'];
